version = 0.1

[default.deploy.parameters]
stack_name = "gamehub-service"
resolve_s3 = false
s3_bucket = "gamehub-service-086723604095-us-west-2-sam-artifacts"
s3_prefix = "gamehub-service"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EnvironmentName=\"prod\" CorsOrigins=\"https://rldojo.net,https://www.rldojo.net,https://d1fqi0i49yjph9.cloudfront.net\" BlogImagesBucket=\"blackjack-web-086723604095-prod\" BlogImagesRegion=\"eu-west-2\" BlogImagesPublicBaseUrl=\"https://d1fqi0i49yjph9.cloudfront.net\" BlogTranslateRegion=\"us-west-2\""
image_repositories = []

[default.global.parameters]
region = "us-west-2"
