export const DYNAMODB_CLIENT = Symbol('DYNAMODB_CLIENT');
export const DYNAMODB_DOCUMENT_CLIENT = Symbol('DYNAMODB_DOCUMENT_CLIENT');
export const ARTICLES_TABLE_NAME = Symbol('ARTICLES_TABLE_NAME');
